Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Users\dngus\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\dngus\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "s1.py", line 16, in sound_alarm
    playsound.playsound(path)
  File "C:\Users\dngus\AppData\Local\Programs\Python\Python37\lib\site-packages\playsound.py", line 35, in _playsoundWin
    winCommand('open "' + sound + '" alias', alias)
  File "C:\Users\dngus\AppData\Local\Programs\Python\Python37\lib\site-packages\playsound.py", line 30, in winCommand
    '\n    ' + errorBuffer.value.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 0: invalid start byte


-> 명령어 입력시 wav파일이름 잘못적음,,, 수정후 정상작동